### PR TITLE
Add Triangular pyramid primitive

### PR DESCRIPTION
**Pull request by sai-barath**
I tried to add @amp1130 as a co-author, but it isn't showing on github for some reason

### CODE REVIEW

**Review by Salamence064 — CHANGES_REQUESTED** [review]
Rename the radius variable (since radius of a triangular pyramid doesn't exist) to distance (or something similar). For the getVertices() function, be sure to not factor in pos when creating the vertices as otherwise it will be double added and the rotation will not be about the triangular pyramids origin. When you do pos + (rot * v[i]) later, it factors in the pos for you. I would also recommend updating the names of the parameters in the constructor to the full word (center, sideLength, theta, and phi) to make it clearer for the user what each parameter is. I would also say to probably make the radius (distance) value public.

**Comment by sai-barath** [comment]
So does that mean that the first time I'm creating the vertices (before applying the rotation), I would just pretend that the center point was the origin of the coordinate system, then do pos + rot * v[i] for each vertex to apply the rotation AND make sure it's about the actual center point instead of the origin?

**Comment by Salamence064** [comment]
Yes, that's exactly right

**Review by Salamence064 — CHANGES_REQUESTED** [review]
E

**Review by Salamence064 — APPROVED** [review]

**Pull request merged**
